//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyndicateIT.Views.Exams.CheckingTags.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _ExamsCheckingTagsFilter_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _ExamsCheckingTagsFilter_cshtml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SyndicateIT.Views.Exams.CheckingTags.App_LocalResources._ExamsCheckingTagsFilte" +
                            "r.cshtml", typeof(_ExamsCheckingTagsFilter_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Tags by Student.
        /// </summary>
        public static string CheckingTagsStudent {
            get {
                return ResourceManager.GetString("CheckingTagsStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string Class_ID {
            get {
                return ResourceManager.GetString("Class_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class is required.
        /// </summary>
        public static string Class_ID_Required {
            get {
                return ResourceManager.GetString("Class_ID_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle.
        /// </summary>
        public static string Cycle_id {
            get {
                return ResourceManager.GetString("Cycle_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle is required.
        /// </summary>
        public static string Cycle_id_Required {
            get {
                return ResourceManager.GetString("Cycle_id_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        public static string Division_ID {
            get {
                return ResourceManager.GetString("Division_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division  is required.
        /// </summary>
        public static string Division_ID_Required {
            get {
                return ResourceManager.GetString("Division_ID_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Class.
        /// </summary>
        public static string EnterClass {
            get {
                return ResourceManager.GetString("EnterClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Cycle.
        /// </summary>
        public static string EnterCycle {
            get {
                return ResourceManager.GetString("EnterCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Division.
        /// </summary>
        public static string EnterDivision {
            get {
                return ResourceManager.GetString("EnterDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no data available.
        /// </summary>
        public static string noavailable {
            get {
                return ResourceManager.GetString("noavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Division.
        /// </summary>
        public static string SelectDivision {
            get {
                return ResourceManager.GetString("SelectDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Students.
        /// </summary>
        public static string ViewStudents {
            get {
                return ResourceManager.GetString("ViewStudents", resourceCulture);
            }
        }
    }
}
