//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyndicateIT.Views.ServiceManagement.Agenda.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _AgendaPartial_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _AgendaPartial_cshtml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SyndicateIT.Views.ServiceManagement.Agenda.App_LocalResources._AgendaPartial.cs" +
                            "html", typeof(_AgendaPartial_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string Agenda {
            get {
                return ResourceManager.GetString("Agenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string Class_ID {
            get {
                return ResourceManager.GetString("Class_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Class field is required..
        /// </summary>
        public static string ClassRequired {
            get {
                return ResourceManager.GetString("ClassRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Course field is required..
        /// </summary>
        public static string CourseRequired {
            get {
                return ResourceManager.GetString("CourseRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle.
        /// </summary>
        public static string Cycle_id {
            get {
                return ResourceManager.GetString("Cycle_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cycle field is required..
        /// </summary>
        public static string CycleRequired {
            get {
                return ResourceManager.GetString("CycleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        public static string Division_ID {
            get {
                return ResourceManager.GetString("Division_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Division field is required..
        /// </summary>
        public static string DivisionRequired {
            get {
                return ResourceManager.GetString("DivisionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Course.
        /// </summary>
        public static string EnterCourse {
            get {
                return ResourceManager.GetString("EnterCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Period Date.
        /// </summary>
        public static string EnterDate {
            get {
                return ResourceManager.GetString("EnterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Date.
        /// </summary>
        public static string PeriodDate {
            get {
                return ResourceManager.GetString("PeriodDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Period Date field is required..
        /// </summary>
        public static string PeriodDateRequired {
            get {
                return ResourceManager.GetString("PeriodDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Class .
        /// </summary>
        public static string SelectClass_Id {
            get {
                return ResourceManager.GetString("SelectClass_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Cycle.
        /// </summary>
        public static string SelectCycle {
            get {
                return ResourceManager.GetString("SelectCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Division.
        /// </summary>
        public static string SelectDivision {
            get {
                return ResourceManager.GetString("SelectDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Title field is required..
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
    }
}
