//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyndicateIT.Views.ServiceManagement.Agenda.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _AgendaDailyPartial_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _AgendaDailyPartial_cshtml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SyndicateIT.Views.ServiceManagement.Agenda.App_LocalResources._AgendaDailyParti" +
                            "al.cshtml", typeof(_AgendaDailyPartial_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Division.
        /// </summary>
        public static string EnterDivision_Id {
            get {
                return ResourceManager.GetString("EnterDivision_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Class.
        /// </summary>
        public static string EnterSearchClass {
            get {
                return ResourceManager.GetString("EnterSearchClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Cycle.
        /// </summary>
        public static string EnterSearchCycle {
            get {
                return ResourceManager.GetString("EnterSearchCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter  Date.
        /// </summary>
        public static string EnterSearchDate {
            get {
                return ResourceManager.GetString("EnterSearchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string lblSearchClass {
            get {
                return ResourceManager.GetString("lblSearchClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle.
        /// </summary>
        public static string lblSearchCycle {
            get {
                return ResourceManager.GetString("lblSearchCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        public static string lblSearchDivision {
            get {
                return ResourceManager.GetString("lblSearchDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Date is required..
        /// </summary>
        public static string RequiredDate {
            get {
                return ResourceManager.GetString("RequiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The  Search Class is required.
        /// </summary>
        public static string RequiredSearchClass {
            get {
                return ResourceManager.GetString("RequiredSearchClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The  Search Cycle is required.
        /// </summary>
        public static string RequiredSearchCycle {
            get {
                return ResourceManager.GetString("RequiredSearchCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The  Search Division  is required.
        /// </summary>
        public static string RequiredSearchDivision {
            get {
                return ResourceManager.GetString("RequiredSearchDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string SearchDate {
            get {
                return ResourceManager.GetString("SearchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Cycle.
        /// </summary>
        public static string SelectCycle {
            get {
                return ResourceManager.GetString("SelectCycle", resourceCulture);
            }
        }
    }
}
