//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyndicateIT.Views.Exams.SignsExam.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _SignsExamSearchPartial_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _SignsExamSearchPartial_cshtml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SyndicateIT.Views.Exams.SignsExam.App_LocalResources._SignsExamSearchPartial.cs" +
                            "html", typeof(_SignsExamSearchPartial_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Course.
        /// </summary>
        public static string EnterCourse_Id {
            get {
                return ResourceManager.GetString("EnterCourse_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Division.
        /// </summary>
        public static string EnterDivision_Id {
            get {
                return ResourceManager.GetString("EnterDivision_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Class.
        /// </summary>
        public static string EnterSearchClass {
            get {
                return ResourceManager.GetString("EnterSearchClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Cycle.
        /// </summary>
        public static string EnterSearchCycle {
            get {
                return ResourceManager.GetString("EnterSearchCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string lblSearchClass {
            get {
                return ResourceManager.GetString("lblSearchClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string lblSearchCourse {
            get {
                return ResourceManager.GetString("lblSearchCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle.
        /// </summary>
        public static string lblSearchCycle {
            get {
                return ResourceManager.GetString("lblSearchCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        public static string lblSearchDivision {
            get {
                return ResourceManager.GetString("lblSearchDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string lblSearchFromDate {
            get {
                return ResourceManager.GetString("lblSearchFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string lblSearchToDate {
            get {
                return ResourceManager.GetString("lblSearchToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Class  is required.
        /// </summary>
        public static string RequiredSearchClass {
            get {
                return ResourceManager.GetString("RequiredSearchClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Course is required.
        /// </summary>
        public static string RequiredSearchCourse {
            get {
                return ResourceManager.GetString("RequiredSearchCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cycle is required.
        /// </summary>
        public static string RequiredSearchCycle {
            get {
                return ResourceManager.GetString("RequiredSearchCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Division is required.
        /// </summary>
        public static string RequiredSearchDivision {
            get {
                return ResourceManager.GetString("RequiredSearchDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Signs Exams.
        /// </summary>
        public static string SearchExams {
            get {
                return ResourceManager.GetString("SearchExams", resourceCulture);
            }
        }
    }
}
