//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyndicateIT.Views.Exams.SignsExam.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _TablePSExamPartial_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _TablePSExamPartial_cshtml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SyndicateIT.Views.Exams.SignsExam.App_LocalResources._TablePSExamPartial.cshtml" +
                            "", typeof(_TablePSExamPartial_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توقيع الادارة.
        /// </summary>
        public static string AdminSignature {
            get {
                return ResourceManager.GetString("AdminSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعدل.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقدير.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : الصف.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدرجة.
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : الشعبة.
        /// </summary>
        public static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعدل.
        /// </summary>
        public static string GeneralAverage {
            get {
                return ResourceManager.GetString("GeneralAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموع العام.
        /// </summary>
        public static string GeneralTotal {
            get {
                return ResourceManager.GetString("GeneralTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المادة.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العلامة القصوى.
        /// </summary>
        public static string MaximumMark {
            get {
                return ResourceManager.GetString("MaximumMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : الاسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : رقم التلميذ .
        /// </summary>
        public static string NumberStudents {
            get {
                return ResourceManager.GetString("NumberStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توقيع الاهل.
        /// </summary>
        public static string ParentSignature {
            get {
                return ResourceManager.GetString("ParentSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخصص للأهل : استلمت بطاقة العلامات هذه بتاريخ  ٠٠/ ٠٠ /  ٢٠١٧.
        /// </summary>
        public static string ParentsNotes {
            get {
                return ResourceManager.GetString("ParentsNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النتيجة.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعاد هذه القسيمة الى المركز.
        /// </summary>
        public static string ReturnNote {
            get {
                return ResourceManager.GetString("ReturnNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekaa Youth Education Center.
        /// </summary>
        public static string SchoolName {
            get {
                return ResourceManager.GetString("SchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مركز الشباب البقاعي التربوي.
        /// </summary>
        public static string SchoolNameAr {
            get {
                return ResourceManager.GetString("SchoolNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عيتا الفخار - راشيا.
        /// </summary>
        public static string SchoolNameArAddr {
            get {
                return ResourceManager.GetString("SchoolNameArAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre D&apos;éducation des Jeunes de la Békaa.
        /// </summary>
        public static string SchoolNameFr {
            get {
                return ResourceManager.GetString("SchoolNameFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات المدرسة.
        /// </summary>
        public static string SchoolNotes {
            get {
                return ResourceManager.GetString("SchoolNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بطاقة العلامات التقويمية للحلقة .
        /// </summary>
        public static string SignExamTitle {
            get {
                return ResourceManager.GetString("SignExamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموع.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
    }
}
