//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyndicateIT.Views.Exams.SignsExam.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _TablePRExamPartial_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _TablePRExamPartial_cshtml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SyndicateIT.Views.Exams.SignsExam.App_LocalResources._TablePRExamPartial.cshtml" +
                            "", typeof(_TablePRExamPartial_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توقيع الادارة.
        /// </summary>
        public static string AdminSignature {
            get {
                return ResourceManager.GetString("AdminSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعدل.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيف.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :الصف.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدرجة.
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :الشعبة.
        /// </summary>
        public static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعدل.
        /// </summary>
        public static string GeneralAverage {
            get {
                return ResourceManager.GetString("GeneralAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموع العام.
        /// </summary>
        public static string GeneralTotal {
            get {
                return ResourceManager.GetString("GeneralTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المادة.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العلامة القصوى.
        /// </summary>
        public static string MaximumMark {
            get {
                return ResourceManager.GetString("MaximumMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :الاسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :رقم التلميذ.
        /// </summary>
        public static string NumberStudents {
            get {
                return ResourceManager.GetString("NumberStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توقيع الاهل.
        /// </summary>
        public static string ParentSignature {
            get {
                return ResourceManager.GetString("ParentSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent&apos;s signature.
        /// </summary>
        public static string ParentSignatureEng {
            get {
                return ResourceManager.GetString("ParentSignatureEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signature des parents.
        /// </summary>
        public static string ParentSignatureFr {
            get {
                return ResourceManager.GetString("ParentSignatureFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات الاهل.
        /// </summary>
        public static string ParentsNotes {
            get {
                return ResourceManager.GetString("ParentsNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parents Notes.
        /// </summary>
        public static string ParentsNotesEng {
            get {
                return ResourceManager.GetString("ParentsNotesEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes du parents.
        /// </summary>
        public static string ParentsNotesFr {
            get {
                return ResourceManager.GetString("ParentsNotesFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النتيجة.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعاد هذه القسيمة الى المركز.
        /// </summary>
        public static string ReturnNote {
            get {
                return ResourceManager.GetString("ReturnNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekaa Youth Eduction Center.
        /// </summary>
        public static string SchoolName {
            get {
                return ResourceManager.GetString("SchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مركز الشباب البقاعي التربوي.
        /// </summary>
        public static string SchoolNameAr {
            get {
                return ResourceManager.GetString("SchoolNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عيتا الفخار - راشيا.
        /// </summary>
        public static string SchoolNameArAddr {
            get {
                return ResourceManager.GetString("SchoolNameArAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre D&apos;education des Jeunes de la Békaa.
        /// </summary>
        public static string SchoolNameFr {
            get {
                return ResourceManager.GetString("SchoolNameFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات .
        /// </summary>
        public static string SchoolNotesAr {
            get {
                return ResourceManager.GetString("SchoolNotesAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        public static string SchoolNotesEng {
            get {
                return ResourceManager.GetString("SchoolNotesEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarque:.
        /// </summary>
        public static string SchoolNotesFr {
            get {
                return ResourceManager.GetString("SchoolNotesFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفصل الاول.
        /// </summary>
        public static string Semester1Ar {
            get {
                return ResourceManager.GetString("Semester1Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Term.
        /// </summary>
        public static string Semester1Eng {
            get {
                return ResourceManager.GetString("Semester1Eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premier Trimestre.
        /// </summary>
        public static string Semester1Fr {
            get {
                return ResourceManager.GetString("Semester1Fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفصل الثاني.
        /// </summary>
        public static string Semester2Ar {
            get {
                return ResourceManager.GetString("Semester2Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second semester Notes.
        /// </summary>
        public static string Semester2Eng {
            get {
                return ResourceManager.GetString("Semester2Eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes de deuxième semester.
        /// </summary>
        public static string Semester2Fr {
            get {
                return ResourceManager.GetString("Semester2Fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفصل الثالث.
        /// </summary>
        public static string Semester3Ar {
            get {
                return ResourceManager.GetString("Semester3Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third semester Notes.
        /// </summary>
        public static string Semester3Eng {
            get {
                return ResourceManager.GetString("Semester3Eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes de troisième semester.
        /// </summary>
        public static string Semester3Fr {
            get {
                return ResourceManager.GetString("Semester3Fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف التقويمي لمرحلة.
        /// </summary>
        public static string SignExamTitle {
            get {
                return ResourceManager.GetString("SignExamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توقيع المربية.
        /// </summary>
        public static string TeacherSignatureAr {
            get {
                return ResourceManager.GetString("TeacherSignatureAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher&apos;s signature.
        /// </summary>
        public static string TeacherSignatureEng {
            get {
                return ResourceManager.GetString("TeacherSignatureEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature de l&apos;enseignant.
        /// </summary>
        public static string TeacherSignatureFr {
            get {
                return ResourceManager.GetString("TeacherSignatureFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموع.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
    }
}
