//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyndicateIT.DataLayer.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Company_Addresses1 = new HashSet<Company_Addresses>();
            this.Company_DocumentExtension = new HashSet<Company_DocumentExtension>();
        }
    
        public int Company_ID { get; set; }
        public string Company_Name { get; set; }
        public string Company_Description { get; set; }
        public string Company_Website { get; set; }
        public string Company_Email { get; set; }
        public string Company_Logo { get; set; }
        public string Reg_Finance { get; set; }
        public string Reg_CNSS { get; set; }
        public bool IS_ACTIVE { get; set; }
        public Nullable<System.DateTimeOffset> ENTRY_DATE { get; set; }
        public Nullable<System.Guid> ENTRY_USER_ID { get; set; }
        public Nullable<System.Guid> MODIFICATION_USER_ID { get; set; }
        public Nullable<System.DateTimeOffset> MODIFICATION_DATE { get; set; }
        public Nullable<int> Company_Type { get; set; }
    
        public virtual Company_Addresses Company_Addresses { get; set; }
        public virtual Company_Type Company_Type1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company_Addresses> Company_Addresses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company_DocumentExtension> Company_DocumentExtension { get; set; }
    }
}
