//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyndicateIT.DataLayer.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Degree_Insurance
    {
        public System.Guid Degree_Insurance_Id { get; set; }
        public string Degree_Insurance_Name { get; set; }
        public bool Is_Active { get; set; }
        public Nullable<System.DateTimeOffset> Entry_Users_Date { get; set; }
        public Nullable<System.DateTimeOffset> Modification_Users_Date { get; set; }
        public string Fts { get; set; }
        public Nullable<System.Guid> Entry_Users_Id { get; set; }
        public Nullable<System.Guid> Modificartion_Id { get; set; }
        public Nullable<System.Guid> Language_Id { get; set; }
        public Nullable<System.Guid> Owner_Id { get; set; }
    }
}
