//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyndicateIT.DataLayer.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string MenuType { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public int MenuItemOrder { get; set; }
        public string MenuItemIndex { get; set; }
        public int MenuItemLevel { get; set; }
        public bool IsMenuItem { get; set; }
    }
}
