//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyndicateIT.DataLayer.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Document_Form_Template
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Document_Form_Template()
        {
            this.T_Document_Form = new HashSet<T_Document_Form>();
        }
    
        public long Id { get; set; }
        public int Document_Form_Sub_Category_Id { get; set; }
        public string Name { get; set; }
        public string Template { get; set; }
        public int NbInput { get; set; }
        public string FileIndexes { get; set; }
        public string Executed_Template { get; set; }
        public bool Is_Publish { get; set; }
        public bool IS_ACTIVE { get; set; }
        public Nullable<System.DateTimeOffset> ENTRY_DATE { get; set; }
        public Nullable<System.Guid> ENTRY_USER_ID { get; set; }
        public Nullable<System.Guid> MODIFICATION_USER_ID { get; set; }
        public Nullable<System.DateTimeOffset> MODIFICATION_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Document_Form> T_Document_Form { get; set; }
        public virtual T_Document_Form_Sub_Category T_Document_Form_Sub_Category { get; set; }
    }
}
