//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyndicateIT.DataLayer.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Document_Form_Data
    {
        public long Form_id { get; set; }
        public int Index { get; set; }
        public string Value { get; set; }
    
        public virtual T_Document_Form T_Document_Form { get; set; }
    }
}
