//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyndicateIT.DataLayer.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Voter_Code
    {
        public System.Guid User_Id { get; set; }
        public string Code { get; set; }
        public int Election_Id { get; set; }
    
        public virtual T_Election T_Election { get; set; }
    }
}
