//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyndicateIT.DataLayer.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User_Contact
    {
        public int User_Contact_ID { get; set; }
        public Nullable<System.Guid> User_ID { get; set; }
        public Nullable<int> COUNTRY_ID { get; set; }
        public Nullable<int> STATE_ID { get; set; }
        public Nullable<int> REGION_ID { get; set; }
        public Nullable<int> CITY_ID { get; set; }
        public string TownShip { get; set; }
        public string Street { get; set; }
        public string Building { get; set; }
        public string Floor { get; set; }
        public string POBox { get; set; }
        public string Fax { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<System.DateTimeOffset> ENTRY_DATE { get; set; }
        public Nullable<System.Guid> ENTRY_USER_ID { get; set; }
        public Nullable<System.Guid> MODIFICATION_USER_ID { get; set; }
        public Nullable<System.DateTimeOffset> MODIFICATION_DATE { get; set; }
        public Nullable<int> Flag { get; set; }
    }
}
