//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyndicateIT.DataLayer.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User_Employment
    {
        public int User_Employment_ID { get; set; }
        public Nullable<System.Guid> User_ID { get; set; }
        public Nullable<int> JOB_ID { get; set; }
        public Nullable<int> SHIFT_ID { get; set; }
        public Nullable<int> COUNTRY_ID { get; set; }
        public Nullable<int> DEPARTMENT_ID { get; set; }
        public Nullable<int> STATUS_ID { get; set; }
        public Nullable<int> LicenseNumber { get; set; }
        public string Grade { get; set; }
        public string Division { get; set; }
        public Nullable<int> EmployeeNumber { get; set; }
        public Nullable<int> HPD { get; set; }
        public Nullable<int> WD { get; set; }
        public Nullable<bool> IS_INTERNATIONAL { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<System.DateTime> LicenseIssuingDate { get; set; }
        public Nullable<System.DateTime> Contract_Date { get; set; }
        public Nullable<System.DateTimeOffset> ENTRY_DATE { get; set; }
        public Nullable<System.Guid> ENTRY_USER_ID { get; set; }
        public Nullable<System.Guid> MODIFICATION_USER_ID { get; set; }
        public Nullable<System.DateTimeOffset> MODIFICATION_DATE { get; set; }
    }
}
