//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyndicateIT.DataLayer.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid User_ID { get; set; }
        public string FirstName { get; set; }
        public string MIddleName { get; set; }
        public string LastName { get; set; }
        public string MotherName { get; set; }
        public string FirstNameName_Ar { get; set; }
        public string MiddleName_Ar { get; set; }
        public string LastName_Ar { get; set; }
        public string MotherName_Ar { get; set; }
        public string ApplicationNumber { get; set; }
        public string RegisteryNumber { get; set; }
        public string RegisteryPlace { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public Nullable<int> Genders_Id { get; set; }
        public Nullable<int> Country_ID { get; set; }
        public Nullable<int> Religions_ID { get; set; }
        public Nullable<int> Maritals_ID { get; set; }
        public Nullable<int> Subjects_ID { get; set; }
        public Nullable<int> Companys_ID { get; set; }
        public Nullable<System.Guid> Roles_ID { get; set; }
        public Nullable<System.Guid> UserReference_ID { get; set; }
        public string Facebook_ID { get; set; }
        public string Google_ID { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Place_Of_Birth { get; set; }
        public string UserName { get; set; }
        public string IDNumber { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> FirstNationality { get; set; }
        public Nullable<int> SecondNationality { get; set; }
        public Nullable<int> Bus_id { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public Nullable<decimal> User_LONGITUDE { get; set; }
        public Nullable<decimal> User_LATITUDE { get; set; }
        public Nullable<bool> IS_BLACKLISTED { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<System.DateTimeOffset> ENTRY_DATE { get; set; }
        public Nullable<System.Guid> ENTRY_USER_ID { get; set; }
        public Nullable<System.Guid> MODIFICATION_USER_ID { get; set; }
        public Nullable<System.DateTimeOffset> MODIFICATION_DATE { get; set; }
        public string AspNetUsers_Id { get; set; }
        public string linkedin { get; set; }
        public string twitter { get; set; }
        public Nullable<int> SpeakingProficiencyArabic { get; set; }
        public Nullable<int> ReadingProficiencyArabic { get; set; }
        public Nullable<int> WritingProficiencyArabic { get; set; }
        public Nullable<int> SpeakingProficiencyAnglais { get; set; }
        public Nullable<int> ReadingProficiencyAnglais { get; set; }
        public Nullable<int> WritingProficiencyAnglais { get; set; }
        public Nullable<int> SpeakingProficiencyFrench { get; set; }
        public Nullable<int> ReadingProficiencyFrench { get; set; }
        public Nullable<int> WritingProficiencyFrench { get; set; }
        public string MobileNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileAlternateNumber { get; set; }
        public string PhoneAlternateNumber { get; set; }
    }
}
